### PR TITLE
replace icons & text with todo-like icons

### PR DESCRIPTION
**Pull request by issackjohn**

### CODE REVIEW

**Comment by issackjohn** [comment]
image

**Comment by issackjohn** [comment]
image
image

**Comment by issackjohn** [comment]
image
image

**Comment by issackjohn** [comment]
image

**Comment by issackjohn** [comment]
@lpardosixtosMs PTAL

**Comment by issackjohn** [comment]
image
Thinking about what to do about the background

**Comment by issackjohn** [comment]
image
I'm not too sure what more to do, adding a border made it look weird.

**Comment by lpardosixtosMs** [comment]
It's fine, resolve the merge conflicts and we'll merge it

**Pull request merged**
