### PR TITLE
add targeted classname

### PR DESCRIPTION
**Pull request by issackjohn**
- [x] angular
- [x] backbone
- [x] jquery
- [x] preact
- [x] react
- [x] react-redux
- [x] svelte
- [x] vue
- [x] es5
- [x] es6
- [x] es6-webpack

### CODE REVIEW

**Comment by lpardosixtosMs** [comment]
For angular we need to make the css match the custom elements in the HTML

**Comment by issackjohn** [comment]
### Check that embedded todomvcs work.
- [x] angular
- [x]  backbone
- [x]  jquery
- [x]  preact
- [x]  react
- [x]  react-redux
- [x]  svelte
- [x]  vue
- [x]  es5
- [x]  es6
- [x]  es6-webpack

### double check regular todomvcs
- [x] angular
- [x]  backbone
- [x]  jquery
- [x]  preact
- [x]  react
- [x]  react-redux
- [x]  svelte
- [x]  vue
- [x]  es5
- [x]  es6
- [x]  es6-webpack

**Comment by issackjohn** [comment]
Jquery has some weird ui issue. also on regular dist. pretty sure this already existed as i recall seeing it before. can check main branch to confirm
image

**Comment by issackjohn** [comment]
for svelte & vue you can enter empty todo elements. randomly came across this, wasn't actively testing this of benchmarks that came before in the list.

**Comment by issackjohn** [comment]
Javascript-es5.
(1) add one item to todolist 
(2) add text to the input box "what needs to be done?" 
(3) click the down arrow to the left of the box to check all todo items, 
(4) the item gets added. 

not sure if this repros on main. repos in the regular dist. I'm not even sure if this is regular behavior.
todo: confirm.

**Comment by issackjohn** [comment]
image
javascript es5, javascript-es6
pressing the 'x' beside another todo item while something is in the text field causes the todo item to be added and the 'x' doesn't remove the item. I think this is because clicking away causes the item to be added.

**Comment by issackjohn** [comment]
Regen regular dist
- [x]  angular
- [x]  backbone
- [x]  jquery
- [x]  preact
- [x]  react
- [x]  react-redux
- [x]  svelte
- [x]  vue
- [x]  es5
- [x]  es6
- [x]  es6-webpack

**Comment by lpardosixtosMs** [comment]
Check targeted css
- [x]  backbone
- [x]  jquery
- [x]  preact
- [x]  react
- [x]  react-redux
- [x]  svelte
- [x]  vue
- [x]  es5
- [x]  es6
- [x]  es6-webpack

**Review by lpardosixtosMs — APPROVED** [review]
LGTM

**Pull request merged**
