### PR TITLE
add purge css and post css to webpack config

### PR DESCRIPTION
**Pull request by issackjohn**

### CODE REVIEW

**Comment by issackjohn** [comment]
image

**Comment by issackjohn** [comment]
Webpack performs operations in a specific order during the build process. 

1. First, it resolves the entry points specified in the configuration and builds a dependency graph of all the modules required by the application. 
2. Then, it processes each module according to the rules specified in the configuration, applying loaders as necessary. Loaders are applied in reverse order, with the last loader in the chain being applied first.
3. After all modules have been processed, webpack generates a bundle for each specified entry point. During this process, plugins can be applied to further modify the generated bundles. The order in which plugins are applied is determined by the order in which they are specified in the configuration.

**Comment by issackjohn** [comment]
"You are using PurgeCSSPlugin to remove unused CSS from your output files, which is a good practice. However, you are passing the path to your index.html file as the only source of content to scan for used selectors. This means that if you have any dynamic content generated by JavaScript or React, PurgeCSS might miss some selectors that are actually used in your app. To avoid this, you should either use the extractors option to specify how to extract selectors from different types of files, or use the safelist option to whitelist the selectors that you don't want PurgeCSS to remove."

**Comment by lpardosixtosMs** [comment]
Applying purge to our index.html is exactly what we want, we can ignore the rest of the source files. Ideally we want to use any minifier plugins after purge has done its job.

**Pull request merged**
